package dev.lounres.halfhat.client.ui.components.game.onlineGame.gameScreen.roundScreen.roundEditing.player.listener


class RealRoundEditingListenerContentComponent : RoundEditingListenerContentComponent